trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - TemperatureWebSite/*

variables:
  buildConfiguration: 'Release'

jobs:
- template: template-webapp-job.yml
  parameters:
    buildConfiguration: $(buildConfiguration)
    projectPath: TemperatureWebSite
    publishPath: TemperatureWebSite/TemperatureWebSite
    webAppName: escalona1811Temp
