trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - TemperatureREST/*

variables:
  buildConfiguration: 'Release'

jobs:
- template: ../template-webapp-job.yml
  parameters:
    buildConfiguration: $(buildConfiguration)
    projectPath: TemperatureREST
    publishPath: TemperatureREST/TemperatureREST
    webAppName: escalona1811TempService
